# Generated by Django 4.1.4 on 2022-12-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZaigoUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
